### PR TITLE
update lead.amount to range, remove parseInt

### PR DESCRIPTION
**Pull request by ros3bud**
Moving towards the needed update referred to in Lendio #28. @alexkwolfe, LGTY?

### CODE REVIEW

**Comment by zalary** [comment]
I'm not Alex, but did you consider writing a test that passes a range and make sure the expected thing happens? :smile:

**Comment by ros3bud** [comment]
Not exactly sure of what to do.

This test should work: 

      it 'should parse amount', ->
        assert.equal integration.request(req(body())).mortgage.loan.amount, 1000-2000

But it most certainly does not. 

Will that work once the type is officially updated to master in the types repo?

**Comment by zalary** [comment]
The other question that comes to mind for me, besides just checking to see if we can pass a range, is if Costco wants a range or exactly what they allow in that field - we may need to take into account multiple scenarios to make sure we accept the right things and pass them the expected thing.

**Comment by ros3bud** [comment]
It's already established that Costco will pass a number for this field. However the type for loan.amount is getting updated to range.

**Comment by zalary** [comment]
Maybe this is a less big deal than I am making it, but it seems like relying on Costco to send a number isn't that safe of a bet when we are changing the leadconduit field, their posting docs will indicate they can send a range.  Since this is inbound maybe that's fine and they can send a range or a number and the handler will handle it, but a least a test to make sure it does what it should do in that case might be worth a stab.  As for why that test doesn't pass, I'm not sure what's up with that.

**Comment by ros3bud** [comment]
I agree, we should make sure that either a number or a range will work as expected. @alexkwolfe - once the type for loan.amount is updated to range would the above test pass?

**Comment by alexkwolfe** [comment]
I don't see any tests in this PR.

**Comment by ros3bud** [comment]
Referring to this one:   

it 'should parse amount', ->
    assert.equal integration.request(req(body())).mortgage.loan.amount, 1000-2000

Not yet implemented as it does not currently pass.

**Comment by alexkwolfe** [comment]
You're doing subtraction there. And the PR no longer does `parseInt`, so I wouldn't expect any sort of integer to be returned in `mortgage.loan.amount`.

```
1000-2000
=> -1000
```

**Comment by ros3bud** [comment]
Per our discussions, @zalary and/or @cgrayson, LGTY? I also went ahead and got rid of any instance of parseInt.

**Comment by cgrayson** [comment]
I steered you wrong in our DM conversation earlier, Lynda. On further consideration, and some test-testing to verify, I think it'll be fine to go ahead and include range tests now. 

That's because what's being returned by `request()` is the straight JavaScript object that's created by that function, without any of the types (or their parsing) applied to it. 

I made a branch of the lendingtree integration with an altered test to illustrate ([here](https://github.com/activeprospect/leadconduit-integration-lendingtree/blob/range_example/spec/unified_long_purchase.coffee#L48-L57), if you want to check it out and play with it):

```coffeescript
  it 'should parse foreclosure filed (in months)', ->
    request = unified.request(req(xml()))
    assert.equal request.mortgage.foreclosure.filed_months_ago, '61-72'

    # note that this is undefined, even though the type of 'mortgage.foreclosure.filed_months_ago' is 'range'
    assert.isUndefined request.mortgage.foreclosure.filed_months_ago.min

    # now apply the types (and their parsing) on this plain JavaScript object
    lead = fields.buildLeadVars(request)
    assert.equal lead.mortgage.foreclosure.filed_months_ago.min, 61 # bingo!
```

That integration is setting `mortgage.foreclosure.filed_months_ago` to the _string_ '61-72', and that's perfectly fine. It's fine because that's a valid format for the `range` type to parse. Note that in the first `assert` (essentially unchanged from master), that's all that's being checked. And the second (new) `assert` shows that there's no such thing as `.min` on `filed_months_ago`, even though it's a `range` type.

That's because it's not really any special type yet. During real lead-handling, the handler will make it into that special type; it looks up the field by the name ("mortgage.foreclosure.filed_months_ago"). If we want to simulate that, we have to do it explicitly in the test code, as I did on the `lead =` line. Et voilà! The last assertion shows there is now a `.min`, and it's even set correctly. :tada: 

I told you earlier via DM that your proposed test wasn't right:
```coffeescript
  it 'should parse amount', ->
    assert equal integration.request(req(body(loan_amount:'1000-2000'))).mortgage.loan.amount, '1000-2000'
```

I said it wasn't right because it wasn't testing the returned `loan.amount` as a range/numeric value. But at that level, testing against a string is okay. And so even though the official type hasn't officially changed and Costco isn't yet sending range values, you can go ahead and add tests to ensure the range string is correctly handled and returned.

**Comment by ros3bud** [comment]
Thanks so much for the information!

**Comment by ros3bud** [comment]
@cgrayson, LGTY?

**Comment by cgrayson** [comment]
I was thinking you could go ahead and add tests to ensure the range string is correctly handled and returned.

**Comment by ros3bud** [comment]
@cgrayson - noted - will get those in here.

**Comment by ros3bud** [comment]
@cgrayson, LGTY?

**Comment by cgrayson** [comment]
:+1:

**Pull request merged**
